import type {
  User,
  Server,
  Channel,
  Message,
  DirectMessage,
  StatusStory,
  Notification,
} from "@/types";

export const currentUserData: User = {
  id: "user-me",
  name: "GnoseonX User",
  email: "user@gnoseonx.com",
  image: "",
  status: "online",
  statusText: "Building with GnoseonX ⚡",
  location: "Jakarta, Indonesia",
  coords: { lat: -6.2088, lng: 106.8456 },
};

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Alice Cipher",
    email: "alice@gnoseonx.com",
    image: "",
    status: "online",
    statusText: "Hacking the mainframe 🔐",
    location: "Tokyo, Japan",
    coords: { lat: 35.6762, lng: 139.6503 },
  },
  {
    id: "user-2",
    name: "Bob Matrix",
    email: "bob@gnoseonx.com",
    image: "",
    status: "idle",
    statusText: "AFK - grabbing coffee ☕",
    location: "Berlin, Germany",
    coords: { lat: 52.52, lng: 13.405 },
  },
  {
    id: "user-3",
    name: "Charlie Pixel",
    email: "charlie@gnoseonx.com",
    image: "",
    status: "dnd",
    statusText: "In deep focus mode 🧠",
    location: "New York, USA",
    coords: { lat: 40.7128, lng: -74.006 },
  },
  {
    id: "user-4",
    name: "Diana Vector",
    email: "diana@gnoseonx.com",
    image: "",
    status: "online",
    statusText: "Designing something beautiful ✨",
    location: "Paris, France",
    coords: { lat: 48.8566, lng: 2.3522 },
  },
  {
    id: "user-5",
    name: "Echo Syntax",
    email: "echo@gnoseonx.com",
    image: "",
    status: "offline",
    statusText: "",
    location: "London, UK",
    coords: { lat: 51.5074, lng: -0.1278 },
  },
  {
    id: "user-6",
    name: "Felix Node",
    email: "felix@gnoseonx.com",
    image: "",
    status: "online",
    statusText: "Streaming code live 🎬",
    location: "Seoul, South Korea",
    coords: { lat: 37.5665, lng: 126.978 },
  },
];

const genChannels = (serverId: string): Channel[] => [
  {
    id: `${serverId}-general`,
    name: "general",
    type: "text",
    serverId,
    description: "General discussion",
    createdAt: new Date(),
  },
  {
    id: `${serverId}-random`,
    name: "random",
    type: "text",
    serverId,
    description: "Random stuff",
    createdAt: new Date(),
  },
  {
    id: `${serverId}-dev`,
    name: "dev-talk",
    type: "text",
    serverId,
    description: "Development discussion",
    createdAt: new Date(),
  },
  {
    id: `${serverId}-voice`,
    name: "Voice Lounge",
    type: "voice",
    serverId,
    description: "Voice channel",
    createdAt: new Date(),
  },
  {
    id: `${serverId}-video`,
    name: "Video Room",
    type: "video",
    serverId,
    description: "Video channel",
    createdAt: new Date(),
  },
];

export const mockServers: Server[] = [
  {
    id: "server-1",
    name: "GnoseonX HQ",
    icon: "⌘",
    ownerId: "user-me",
    channels: genChannels("server-1"),
    members: [currentUserData, ...mockUsers.slice(0, 4)],
    createdAt: new Date(),
  },
  {
    id: "server-2",
    name: "ASCII Devs",
    icon: "▸",
    ownerId: "user-1",
    channels: genChannels("server-2"),
    members: [currentUserData, ...mockUsers.slice(1, 5)],
    createdAt: new Date(),
  },
  {
    id: "server-3",
    name: "Pixel Art Club",
    icon: "◈",
    ownerId: "user-4",
    channels: genChannels("server-3"),
    members: [currentUserData, ...mockUsers],
    createdAt: new Date(),
  },
  {
    id: "server-4",
    name: "Code Warriors",
    icon: "⚔",
    ownerId: "user-2",
    channels: genChannels("server-4"),
    members: [currentUserData, ...mockUsers.slice(2)],
    createdAt: new Date(),
  },
];

const timeAgo = (mins: number) =>
  new Date(Date.now() - mins * 60 * 1000);

export const mockMessages: Message[] = [
  {
    id: "msg-1",
    content: "Welcome to GnoseonX! ═══════════════╗",
    senderId: "user-1",
    senderName: "Alice Cipher",
    type: "system",
    channelId: "server-1-general",
    reactions: [],
    edited: false,
    createdAt: timeAgo(120),
  },
  {
    id: "msg-2",
    content: "Hey everyone! Just joined this server. The neumorphism theme looks amazing! ░▒▓█",
    senderId: "user-2",
    senderName: "Bob Matrix",
    type: "text",
    channelId: "server-1-general",
    reactions: [{ emoji: "🔥", users: ["user-1", "user-me"] }],
    edited: false,
    createdAt: timeAgo(90),
  },
  {
    id: "msg-3",
    content: "Thanks Bob! Check out the ASCII decorations ╔═══╗\n║ GX ║\n╚═══╝",
    senderId: "user-1",
    senderName: "Alice Cipher",
    type: "text",
    channelId: "server-1-general",
    reactions: [{ emoji: "✨", users: ["user-2", "user-3"] }],
    edited: false,
    createdAt: timeAgo(85),
  },
  {
    id: "msg-4",
    content: "The video call feature is so smooth! Just tested it with Diana 📹",
    senderId: "user-3",
    senderName: "Charlie Pixel",
    type: "text",
    channelId: "server-1-general",
    reactions: [],
    edited: false,
    createdAt: timeAgo(60),
  },
  {
    id: "msg-5",
    content: "Has anyone tried the location tracking? It shows my general area as Tokyo 🗼",
    senderId: "user-1",
    senderName: "Alice Cipher",
    type: "text",
    channelId: "server-1-general",
    reactions: [{ emoji: "🌏", users: ["user-me"] }],
    edited: false,
    createdAt: timeAgo(45),
  },
  {
    id: "msg-6",
    content: "I'm loving the status stories feature! Just posted mine ⚡",
    senderId: "user-4",
    senderName: "Diana Vector",
    type: "text",
    channelId: "server-1-general",
    reactions: [
      { emoji: "💜", users: ["user-1", "user-2"] },
      { emoji: "🎨", users: ["user-me"] },
    ],
    edited: false,
    createdAt: timeAgo(30),
  },
  {
    id: "msg-7",
    content: "┌──────────────────────────┐\n│  PRO TIP: Use Ctrl+K    │\n│  for quick navigation!  │\n└──────────────────────────┘",
    senderId: "user-me",
    senderName: "GnoseonX User",
    type: "text",
    channelId: "server-1-general",
    reactions: [{ emoji: "👍", users: ["user-1", "user-2", "user-3", "user-4"] }],
    edited: false,
    createdAt: timeAgo(15),
  },
  {
    id: "msg-8",
    content: "Who's up for a group voice call? Let's hop in the Voice Lounge! 🎙️",
    senderId: "user-6",
    senderName: "Felix Node",
    type: "text",
    channelId: "server-1-general",
    reactions: [{ emoji: "🎤", users: ["user-1"] }],
    edited: false,
    createdAt: timeAgo(5),
  },
];

export const mockDMs: DirectMessage[] = [
  {
    id: "dm-1",
    participants: [currentUserData, mockUsers[0]],
    lastMessage: {
      id: "dm-msg-1",
      content: "Hey! Want to check out the new ASCII art pack? 🎨",
      senderId: "user-1",
      senderName: "Alice Cipher",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(10),
    },
    unreadCount: 2,
    createdAt: timeAgo(200),
  },
  {
    id: "dm-2",
    participants: [currentUserData, mockUsers[1]],
    lastMessage: {
      id: "dm-msg-2",
      content: "The coffee is great here in Berlin ☕",
      senderId: "user-2",
      senderName: "Bob Matrix",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(30),
    },
    unreadCount: 0,
    createdAt: timeAgo(500),
  },
  {
    id: "dm-3",
    participants: [currentUserData, mockUsers[3]],
    lastMessage: {
      id: "dm-msg-3",
      content: "Check out my latest design! ✨",
      senderId: "user-4",
      senderName: "Diana Vector",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(60),
    },
    unreadCount: 1,
    createdAt: timeAgo(300),
  },
  {
    id: "dm-4",
    participants: [currentUserData, mockUsers[4]],
    lastMessage: {
      id: "dm-msg-4",
      content: "I'll be back online tomorrow!",
      senderId: "user-5",
      senderName: "Echo Syntax",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(180),
    },
    unreadCount: 0,
    createdAt: timeAgo(400),
  },
];

export const mockDMMessages: Record<string, Message[]> = {
  "dm-1": [
    {
      id: "dm1-m1",
      content: "Hey Alice! How's it going? ░▒▓",
      senderId: "user-me",
      senderName: "GnoseonX User",
      dmId: "dm-1",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(60),
    },
    {
      id: "dm1-m2",
      content: "Great! Just finished a new ASCII art collection 🎨",
      senderId: "user-1",
      senderName: "Alice Cipher",
      dmId: "dm-1",
      type: "text",
      reactions: [{ emoji: "🔥", users: ["user-me"] }],
      edited: false,
      createdAt: timeAgo(55),
    },
    {
      id: "dm1-m3",
      content: "That sounds awesome! Can you share some?",
      senderId: "user-me",
      senderName: "GnoseonX User",
      dmId: "dm-1",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(50),
    },
    {
      id: "dm1-m4",
      content: "Sure! Here's one:\n╔══════════════╗\n║  ★ GnoseonX ★  ║\n║   ◇◇◇◇◇◇◇   ║\n╚══════════════╝",
      senderId: "user-1",
      senderName: "Alice Cipher",
      dmId: "dm-1",
      type: "text",
      reactions: [{ emoji: "✨", users: ["user-me"] }],
      edited: false,
      createdAt: timeAgo(45),
    },
    {
      id: "dm1-m5",
      content: "Hey! Want to check out the new ASCII art pack? 🎨",
      senderId: "user-1",
      senderName: "Alice Cipher",
      dmId: "dm-1",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(10),
    },
  ],
  "dm-2": [
    {
      id: "dm2-m1",
      content: "Bob! How's Berlin treating you?",
      senderId: "user-me",
      senderName: "GnoseonX User",
      dmId: "dm-2",
      type: "text",
      reactions: [],
      edited: false,
      createdAt: timeAgo(120),
    },
    {
      id: "dm2-m2",
      content: "The coffee is great here in Berlin ☕",
      senderId: "user-2",
      senderName: "Bob Matrix",
      dmId: "dm-2",
      type: "text",
      reactions: [{ emoji: "☕", users: ["user-me"] }],
      edited: false,
      createdAt: timeAgo(30),
    },
  ],
};

export const mockStories: StatusStory[] = [
  {
    id: "story-1",
    userId: "user-1",
    userName: "Alice Cipher",
    text: "Just deployed my new project! 🚀\n\n╔═══════════╗\n║  v2.0.0   ║\n╚═══════════╝",
    bgColor: "from-violet-400 to-lava-300",
    createdAt: timeAgo(30),
    expiresAt: new Date(Date.now() + 23 * 60 * 60 * 1000),
    viewers: ["user-me", "user-2"],
  },
  {
    id: "story-2",
    userId: "user-4",
    userName: "Diana Vector",
    text: "New design incoming! ✨🎨",
    bgColor: "from-neon-300 to-violet-300",
    createdAt: timeAgo(120),
    expiresAt: new Date(Date.now() + 21 * 60 * 60 * 1000),
    viewers: ["user-me"],
  },
  {
    id: "story-3",
    userId: "user-6",
    userName: "Felix Node",
    text: "Live coding session starts in 1 hour!\n\n▶ twitch.tv/felixnode",
    bgColor: "from-lava-300 to-neon-300",
    createdAt: timeAgo(60),
    expiresAt: new Date(Date.now() + 22 * 60 * 60 * 1000),
    viewers: [],
  },
  {
    id: "story-me",
    userId: "user-me",
    userName: "GnoseonX User",
    text: "Building with GnoseonX ⚡\n\n░▒▓ CODING MODE ▓▒░",
    bgColor: "from-violet-300 to-neon-300",
    createdAt: timeAgo(45),
    expiresAt: new Date(Date.now() + 22.5 * 60 * 60 * 1000),
    viewers: ["user-1", "user-4"],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    type: "message",
    title: "Alice Cipher",
    body: "sent you a message in GnoseonX HQ",
    fromUser: mockUsers[0],
    read: false,
    createdAt: timeAgo(5),
  },
  {
    id: "notif-2",
    type: "mention",
    title: "Diana Vector",
    body: "mentioned you in #general",
    fromUser: mockUsers[3],
    read: false,
    createdAt: timeAgo(15),
  },
  {
    id: "notif-3",
    type: "status",
    title: "Felix Node",
    body: "posted a new status story",
    fromUser: mockUsers[5],
    read: true,
    createdAt: timeAgo(60),
  },
];
